__Number 5__

A vector is given. The aim of this question is to ensure that a new vector is gotten that has the same direction as the initial vector but a different magnitude.

In [1]:
# Import numpy, pandas, matplotlib.plt and seaborn
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
#sns.set_theme(style="darkgrid")     # Set the format for diagrams

In [2]:
# Set the values for A, B and C
A, B, C = [21, 11, 4]

# Vector x is given and the unit vector is gotten by dividing x through by the magnitude of x
x = np.array([[A],[1], [B]])
unit_vector = x/np.linalg.norm(x)
x, unit_vector

(array([[21],
        [ 1],
        [11]]),
 array([[0.88504448],
        [0.04214498],
        [0.46359473]]))

In [3]:
# Multiply the unit vector by C to get a value equal in magnitude to C
vector_with_magnitude_c = C * unit_vector
vector_with_magnitude_c.round(decimals=3)

array([[3.54 ],
       [0.169],
       [1.854]])

In [4]:
# This is to confirm that the new vector has a magnitude of value C
np.linalg.norm(vector_with_magnitude_c).round(decimals=4) == C

True